//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROJ_INTER_BC4S
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORCAMENTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ORCAMENTO()
        {
            this.PROD_ORCAMENTO = new HashSet<PROD_ORCAMENTO>();
            this.REG_SERV_ORCAMENTO = new HashSet<REG_SERV_ORCAMENTO>();
        }
    
        public int ID { get; set; }
        public int ID_FUNCIONARIO { get; set; }
        public int ID_CLIENTE { get; set; }
        public double VALOR_TOTAL { get; set; }
        public Nullable<System.DateTime> DATA_ORC { get; set; }
        public string STATUS { get; set; }
    
        public virtual LOGIN LOGIN { get; set; }
        public virtual PESSOA PESSOA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROD_ORCAMENTO> PROD_ORCAMENTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REG_SERV_ORCAMENTO> REG_SERV_ORCAMENTO { get; set; }
    }
}
