//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROJ_INTER_BC4S
{
    using System;
    using System.Collections.Generic;
    
    public partial class PESSOA
    {
        public int ID { get; set; }
        public string NOME { get; set; }
        public string LOGRADOURO { get; set; }
        public int NUM_LOGRADOURO { get; set; }
        public string BAIRRO { get; set; }
        public string COMPLEMENTO { get; set; }
        public int CEP { get; set; }
        public string CPF { get; set; }
        public string EMAIL { get; set; }
        public string TELEFONE { get; set; }
    
        public virtual CLIENTE CLIENTE { get; set; }
        public virtual FUNCIONARIO FUNCIONARIO { get; set; }
    }
}
