//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROJ_INTER_BC4S
{
    using System;
    using System.Collections.Generic;
    
    public partial class TELEFONE_FABRICANTE
    {
        public int ID { get; set; }
        public int TELEFONE { get; set; }
    
        public virtual FABRICANTE FABRICANTE { get; set; }
    }
}
